#variables
@baseUrl =http://localhost:3333

#health check
GET {{baseUrl}}/health

###
#get rooms
# @name getRoom 

GET {{baseUrl}}/rooms

###

#Create Rooms
# @name createRoom 
POST {{baseUrl}}/rooms
Accept: application/json,
Content-Type: application/json

{
    "name":"Sala de teste",
    "description": "Essa sala é de teste"
}
###
@roomId = {{createRoom.response.body.$.roomId}}

###
#Get rooms questions
# @name getRoomQuestions 

GET {{baseUrl}}/rooms/{{roomId}}/questions


###

#Create Questions
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Accept: application/json,
Content-Type: application/json

{
    "question":"Batata é doce?"
}